// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQBfCzt8DhBd3kxoxS5Yj_HT8bnE_UhxA',
    appId: '1:993820244946:web:8f942f7879921d130d660b',
    messagingSenderId: '993820244946',
    projectId: 'flutterfitnessapp-67e62',
    authDomain: 'flutterfitnessapp-67e62.firebaseapp.com',
    storageBucket: 'flutterfitnessapp-67e62.appspot.com',
    measurementId: 'G-E564RN5RM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhgC71bYaMNTfi1TUrdJiMMFEf8lBD3yE',
    appId: '1:993820244946:android:30db4c84c2d410a10d660b',
    messagingSenderId: '993820244946',
    projectId: 'flutterfitnessapp-67e62',
    storageBucket: 'flutterfitnessapp-67e62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB812VckXjtEcVYrrYCEUbA1eH3kcsVAyE',
    appId: '1:993820244946:ios:c5cfca142b74be000d660b',
    messagingSenderId: '993820244946',
    projectId: 'flutterfitnessapp-67e62',
    storageBucket: 'flutterfitnessapp-67e62.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
