// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl-t-x71nEqAhhde3YQcoK2wTC6Kl3hMU',
    appId: '1:705452369457:web:e918ac1abf04d6acd59710',
    messagingSenderId: '705452369457',
    projectId: 'flutterfitnessapp-cbb41',
    authDomain: 'flutterfitnessapp-cbb41.firebaseapp.com',
    storageBucket: 'flutterfitnessapp-cbb41.appspot.com',
    measurementId: 'G-XLQTN9QGCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDjBGUPNqX1LwNs4i2s2FRYfCqfQYFthg',
    appId: '1:705452369457:android:d03f7a5291e16a7ad59710',
    messagingSenderId: '705452369457',
    projectId: 'flutterfitnessapp-cbb41',
    storageBucket: 'flutterfitnessapp-cbb41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5rAz_gTj7MqLThITdtKEWuKxcIqZDEJE',
    appId: '1:705452369457:ios:d0bafd28612732e4d59710',
    messagingSenderId: '705452369457',
    projectId: 'flutterfitnessapp-cbb41',
    storageBucket: 'flutterfitnessapp-cbb41.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
