name: user_repository
description: Dart package which manages the user
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  cloud_functions: ^4.6.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  cloud_firestore_web: ^3.10.5
  flutter_bloc: ^8.1.4
  google_mlkit_commons: ^0.6.0
  image_picker: ^1.0.2
  camera: ^0.10.5+3
  path: ^1.8.2
  bloc: ^8.1.3
  path_provider: ^2.1.0
  equatable: ^2.0.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true