name: flutter_application_1
description: A Flutter plugin to use Google's ML Kit Pose Detection to detect the pose of a subject's body in real time from a continuous video or static image.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # path: any
  firebase_core: ^2.25.4
  cloud_functions: ^4.6.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  cloud_firestore_web: ^3.10.5
  flutter_bloc: ^8.1.4
  google_mlkit_commons: ^0.6.0
  image_picker: ^1.0.2
  camera: ^0.10.5+3
  path: ^1.8.2
  bloc: ^8.1.3
  path_provider: ^2.1.0
  equatable: ^2.0.5
  google_mlkit_pose_detection:
    path: ../google_mlkit_pose_detection

  cupertino_icons: ^1.0.2
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/onboarding/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 700
